// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace JedinicnoTESTIRANJE
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// PravokutnikUItest - Use 'PravokutnikUItestParams' to pass parameters into this method.
        /// </summary>
        public void PravokutnikUItest()
        {
            #region Variable Declarations
            WinButton uIPravokutnikButton = this.UIPočetnaformaWindow.UIPravokutnikWindow.UIPravokutnikButton;
            WinEdit uITxtStranicaAEdit = this.UIIzračungeometrijskihWindow.UIItem000Window.UITxtStranicaAEdit;
            WinEdit uITxtStranicaBEdit = this.UIIzračungeometrijskihWindow.UIItem000Window1.UITxtStranicaBEdit;
            WinButton uIIzračunajButton = this.UIIzračungeometrijskihWindow.UIIzračunajWindow.UIIzračunajButton;
            #endregion

            // Click 'Pravokutnik' button
            Mouse.Click(uIPravokutnikButton, new Point(178, 31));

            // Type '4' in 'txtStranicaA' text box
            uITxtStranicaAEdit.Text = this.PravokutnikUItestParams.UITxtStranicaAEditText;

            // Type '5' in 'txtStranicaB' text box
            uITxtStranicaBEdit.Text = this.PravokutnikUItestParams.UITxtStranicaBEditText;

            // Click 'Izračunaj' button
            Mouse.Click(uIIzračunajButton, new Point(64, 7));
        }
        
        /// <summary>
        /// PravokutnikUItestAssert - Use 'PravokutnikUItestAssertExpectedValues' to pass parameters into this method.
        /// </summary>
        public void PravokutnikUItestAssert()
        {
            #region Variable Declarations

            WinEdit uITxtPovrsinaEdit = this.UIIzračungeometrijskihWindow.UIItem000Window3.UITxtPovrsinaEdit;
            WinEdit uITxtOpsegEdit = this.UIIzračungeometrijskihWindow.UIItem000Window4.UITxtOpsegEdit;
            #endregion

           

            // Verify that the 'ControlType' property of 'txtPovrsina' text box equals '"20"'
            Assert.AreEqual(this.PravokutnikUItestAssertExpectedValues.UITxtPovrsinaEditControlType, uITxtPovrsinaEdit.ControlType.ToString(), "Površina nije 20!");

            // Verify that the 'ControlType' property of 'txtOpseg' text box equals '"18"'
            Assert.AreEqual(this.PravokutnikUItestAssertExpectedValues.UITxtOpsegEditControlType, uITxtOpsegEdit.ControlType.ToString(), "Opseg nije točan!");
        }
        
        #region Properties
        public virtual PravokutnikUItestParams PravokutnikUItestParams
        {
            get
            {
                if ((this.mPravokutnikUItestParams == null))
                {
                    this.mPravokutnikUItestParams = new PravokutnikUItestParams();
                }
                return this.mPravokutnikUItestParams;
            }
        }
        
        public virtual PravokutnikUItestAssertExpectedValues PravokutnikUItestAssertExpectedValues
        {
            get
            {
                if ((this.mPravokutnikUItestAssertExpectedValues == null))
                {
                    this.mPravokutnikUItestAssertExpectedValues = new PravokutnikUItestAssertExpectedValues();
                }
                return this.mPravokutnikUItestAssertExpectedValues;
            }
        }
        
        public UIPočetnaformaWindow UIPočetnaformaWindow
        {
            get
            {
                if ((this.mUIPočetnaformaWindow == null))
                {
                    this.mUIPočetnaformaWindow = new UIPočetnaformaWindow();
                }
                return this.mUIPočetnaformaWindow;
            }
        }
        
        public UIIzračungeometrijskihWindow UIIzračungeometrijskihWindow
        {
            get
            {
                if ((this.mUIIzračungeometrijskihWindow == null))
                {
                    this.mUIIzračungeometrijskihWindow = new UIIzračungeometrijskihWindow();
                }
                return this.mUIIzračungeometrijskihWindow;
            }
        }
        #endregion
        
        #region Fields
        private PravokutnikUItestParams mPravokutnikUItestParams;
        
        private PravokutnikUItestAssertExpectedValues mPravokutnikUItestAssertExpectedValues;
        
        private UIPočetnaformaWindow mUIPočetnaformaWindow;
        
        private UIIzračungeometrijskihWindow mUIIzračungeometrijskihWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PravokutnikUItest'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class PravokutnikUItestParams
    {
        
        #region Fields
        /// <summary>
        /// Type '4' in 'txtStranicaA' text box
        /// </summary>
        public string UITxtStranicaAEditText = "4";
        
        /// <summary>
        /// Type '5' in 'txtStranicaB' text box
        /// </summary>
        public string UITxtStranicaBEditText = "5";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PravokutnikUItestAssert'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class PravokutnikUItestAssertExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'txtDijagonala' text box equals '6,403124'
        /// </summary>
        public string UITxtDijagonalaEditControlType = "6,403124";
        
        /// <summary>
        /// Verify that the 'ControlType' property of 'txtPovrsina' text box equals '20'
        /// </summary>
        public string UITxtPovrsinaEditControlType = "20";
        
        /// <summary>
        /// Verify that the 'ControlType' property of 'txtOpseg' text box equals '18'
        /// </summary>
        public string UITxtOpsegEditControlType = "18";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIPočetnaformaWindow : WinWindow
    {
        
        public UIPočetnaformaWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Početna forma";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Početna forma");
            #endregion
        }
        
        #region Properties
        public UIPravokutnikWindow UIPravokutnikWindow
        {
            get
            {
                if ((this.mUIPravokutnikWindow == null))
                {
                    this.mUIPravokutnikWindow = new UIPravokutnikWindow(this);
                }
                return this.mUIPravokutnikWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIPravokutnikWindow mUIPravokutnikWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIPravokutnikWindow : WinWindow
    {
        
        public UIPravokutnikWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnPravokutnik";
            this.WindowTitles.Add("Početna forma");
            #endregion
        }
        
        #region Properties
        public WinButton UIPravokutnikButton
        {
            get
            {
                if ((this.mUIPravokutnikButton == null))
                {
                    this.mUIPravokutnikButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIPravokutnikButton.SearchProperties[WinButton.PropertyNames.Name] = "Pravokutnik";
                    this.mUIPravokutnikButton.WindowTitles.Add("Početna forma");
                    #endregion
                }
                return this.mUIPravokutnikButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIPravokutnikButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIIzračungeometrijskihWindow : WinWindow
    {
        
        public UIIzračungeometrijskihWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Izračun geometrijskih svojstava pravokutnika";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
            #endregion
        }
        
        #region Properties
        public UIItem000Window UIItem000Window
        {
            get
            {
                if ((this.mUIItem000Window == null))
                {
                    this.mUIItem000Window = new UIItem000Window(this);
                }
                return this.mUIItem000Window;
            }
        }
        
        public UIItem000Window1 UIItem000Window1
        {
            get
            {
                if ((this.mUIItem000Window1 == null))
                {
                    this.mUIItem000Window1 = new UIItem000Window1(this);
                }
                return this.mUIItem000Window1;
            }
        }
        
        public UIIzračunajWindow UIIzračunajWindow
        {
            get
            {
                if ((this.mUIIzračunajWindow == null))
                {
                    this.mUIIzračunajWindow = new UIIzračunajWindow(this);
                }
                return this.mUIIzračunajWindow;
            }
        }
        
        public UIItem000Window2 UIItem000Window2
        {
            get
            {
                if ((this.mUIItem000Window2 == null))
                {
                    this.mUIItem000Window2 = new UIItem000Window2(this);
                }
                return this.mUIItem000Window2;
            }
        }
        
        public UIItem000Window3 UIItem000Window3
        {
            get
            {
                if ((this.mUIItem000Window3 == null))
                {
                    this.mUIItem000Window3 = new UIItem000Window3(this);
                }
                return this.mUIItem000Window3;
            }
        }
        
        public UIItem000Window4 UIItem000Window4
        {
            get
            {
                if ((this.mUIItem000Window4 == null))
                {
                    this.mUIItem000Window4 = new UIItem000Window4(this);
                }
                return this.mUIItem000Window4;
            }
        }
        #endregion
        
        #region Fields
        private UIItem000Window mUIItem000Window;
        
        private UIItem000Window1 mUIItem000Window1;
        
        private UIIzračunajWindow mUIIzračunajWindow;
        
        private UIItem000Window2 mUIItem000Window2;
        
        private UIItem000Window3 mUIItem000Window3;
        
        private UIItem000Window4 mUIItem000Window4;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItem000Window : WinWindow
    {
        
        public UIItem000Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtStranicaA";
            this.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtStranicaAEdit
        {
            get
            {
                if ((this.mUITxtStranicaAEdit == null))
                {
                    this.mUITxtStranicaAEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtStranicaAEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Stranica B:";
                    this.mUITxtStranicaAEdit.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
                    #endregion
                }
                return this.mUITxtStranicaAEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtStranicaAEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItem000Window1 : WinWindow
    {
        
        public UIItem000Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtStranicaB";
            this.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtStranicaBEdit
        {
            get
            {
                if ((this.mUITxtStranicaBEdit == null))
                {
                    this.mUITxtStranicaBEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtStranicaBEdit.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
                    #endregion
                }
                return this.mUITxtStranicaBEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtStranicaBEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIIzračunajWindow : WinWindow
    {
        
        public UIIzračunajWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnIzracunaj";
            this.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
            #endregion
        }
        
        #region Properties
        public WinButton UIIzračunajButton
        {
            get
            {
                if ((this.mUIIzračunajButton == null))
                {
                    this.mUIIzračunajButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIIzračunajButton.SearchProperties[WinButton.PropertyNames.Name] = "Izračunaj";
                    this.mUIIzračunajButton.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
                    #endregion
                }
                return this.mUIIzračunajButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIIzračunajButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItem000Window2 : WinWindow
    {
        
        public UIItem000Window2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtDijagonala";
            this.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtDijagonalaEdit
        {
            get
            {
                if ((this.mUITxtDijagonalaEdit == null))
                {
                    this.mUITxtDijagonalaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtDijagonalaEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Površina:";
                    this.mUITxtDijagonalaEdit.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
                    #endregion
                }
                return this.mUITxtDijagonalaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtDijagonalaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItem000Window3 : WinWindow
    {
        
        public UIItem000Window3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtPovrsina";
            this.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtPovrsinaEdit
        {
            get
            {
                if ((this.mUITxtPovrsinaEdit == null))
                {
                    this.mUITxtPovrsinaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtPovrsinaEdit.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
                    #endregion
                }
                return this.mUITxtPovrsinaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtPovrsinaEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItem000Window4 : WinWindow
    {
        
        public UIItem000Window4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtOpseg";
            this.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtOpsegEdit
        {
            get
            {
                if ((this.mUITxtOpsegEdit == null))
                {
                    this.mUITxtOpsegEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtOpsegEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Opseg:";
                    this.mUITxtOpsegEdit.WindowTitles.Add("Izračun geometrijskih svojstava pravokutnika");
                    #endregion
                }
                return this.mUITxtOpsegEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtOpsegEdit;
        #endregion
    }
}
