//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3_1_EvidencijaStudenataX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.AktivnostiStudenta = new HashSet<AktivnostStudenta>();
        }
    
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Status { get; set; }
        public string OdabraniModel { get; set; }
        public string Email { get; set; }
        public string Napomena { get; set; }
        public Nullable<int> TimId { get; set; }
    
        public virtual ICollection<AktivnostStudenta> AktivnostiStudenta { get; set; }
        public virtual Tim Tim { get; set; }
    }
}
