//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3_1_EvidencijaStudenataX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipAktivnosti
    {
        public TipAktivnosti()
        {
            this.Aktivnosti = new HashSet<Aktivnost>();
        }
    
        public int Id { get; set; }
        public string Tip { get; set; }
    
        public virtual ICollection<Aktivnost> Aktivnosti { get; set; }
    }
}
